services:
  php:
    build:
      context: .
      dockerfile: docker/dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
  composer:
    profiles:
      - composer
    build:
      context: .
      dockerfile: docker/dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html

volumes:
  db-data: